### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MatthewKosloski** [tomchentw/react-google-maps#338]
I tried to run the `simple-map` example, but I got the following error when I tried to move around in the map:

    Uncaught RangeError: Maximum call stack size exceeded

All my code is the same thing you have, except I put in my API key:

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing&key=[MY_API_KEY]"></script>

**Comment by ranleung** [comment]
getting the same problem

**Comment by farhd** [comment]
same problem, but default version:
`<script src="https://maps.googleapis.com/maps/api/js"></script>`

**Comment by MatthewKosloski** [comment]
@ranleung @farhd I found a really simple Google Maps React component.  It's called [GMaps](https://github.com/MicheleBertoli/react-gmaps).  The author is pretty good at responding to any questions you have, just create an issue!

**Comment by tomchentw** [comment]
This is a know bug for 4.x and 5.x on React 15. It's fixed in 6.0.0.

 [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by hscharitzer** [comment]
I wanted to chime in and add that this error still occurs on 8.3.2 when following all instructions (https://tomchentw.github.io/react-google-maps/#installation) up to Step 4.

The reason turns out to be a missing 
`defaultCenter={{ lat: 48.124039, lng: 15.8339266 }}`

(I found the solution to this through https://stackoverflow.com/questions/15671480/uncaught-rangeerror-maximum-call-stack-size-exceeded-google-maps-when-i-try-to)

**Comment by nojaf** [comment]
I'm also getting the `RangeError`:
```js
import React from "react";
import { GoogleMap, withGoogleMap } from "react-google-maps";

const MyMap = withGoogleMap(props => {
    console.log(props);
    const leOnClick = ev => {
        console.log(ev.latLng);
        if(props.onClick){
            props.onClick(ev.latLng);
        }
    }

    const defaultCenter = new google.maps.LatLng(-34.397, 150.644);

    return <GoogleMap defaultZoom={8}  defaultCenter={defaultCenter} onClick={leOnClick}></GoogleMap>
});


export function myMap(onClick) {
    console.log('myMap');
    return <MyMap containerElement={<div style={{ height: `400px` }} />}
        mapElement={<div style={{ height: `100%` }} onClick={onClick} />} />
}
```

The props log is an empty object. Gmaps script is added in the `<head>` of my page. What am I missing here?
