### ISSUE TITLE
OverlayView loses other libraries context

### ISSUE THREAD

**Issue by tomasz89nowak** [tomchentw/react-google-maps#578]
I'm using react material-ui lib with react-google-maps.
When I'm trying to nest any material-ui component, eg. List, into OverlayView, I get this error:

> Warning: Failed context type: The context `muiTheme` is marked as required in `List`, but its value is `undefined`.

In whole application, including other react-google-maps components muiTheme exist in the context.

**Comment by oshalygin** [comment]
hrmm yeah this could def be an issue.  I'll take a look.

Out of curiosity, have you tried to pass it down as props from the parent context?

**Comment by tomasz89nowak** [comment]
Yes I tried and it is not working.

**Comment by oshalygin** [comment]
thanks @tomasz89nowak i'll look at it shortly.

**Comment by emilsgulbis** [comment]
Any upates here?

**Comment by oshalygin** [comment]
I was able to confirm this, seems like a known issue.  There are also a number of big changes in play for the material-ui library(1.0 coming soon).  I'm tempted to defer until they've released 1.0 so we can accommodate that release as opposed to trying to support 0.XX

**Comment by emilsgulbis** [comment]
Hey! I think it's not problem with material ui, but with OverlayView context. 
Im using isomorphic-style-loader and it doesnt work OverlayView..

**Comment by oshalygin** [comment]
Alright I'll mark this as an issue that we can dev against

**Comment by emilsgulbis** [comment]
![screen shot 2017-09-06 at 13 48 37](https://user-images.githubusercontent.com/3534160/30108209-2b62c29c-930a-11e7-829a-bde1650783e5.png)

Here is sceenshot of Chrome browser **React** dev tool - **Overlayview** is rendered outside **App**

**Comment by tomchentw** [comment]
Fixed in v8.0.0. Please try the new version.

https://tomchentw.github.io/react-google-maps/#!/OverlayView

**Comment by AustrisC** [comment]
The issue still occurs in version 8.5.0.
OverlayView children are missing context when using isomorphic-style-loader.
